# Generated by Django 2.1.3 on 2018-11-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Author', max_length=200)),
                ('alias', models.CharField(help_text='Alias of the author, optional', max_length=50)),
                ('author_image', models.ImageField(help_text='Image of the Manga', upload_to='media/root')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Genre of the Manga', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Manga', max_length=200)),
                ('image', models.ImageField(help_text='Image of the Manga', upload_to='media/root')),
                ('resume', models.TextField(help_text='Summary', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mangaLibrary.Author')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='mangaLibrary.Genre')),
            ],
        ),
    ]
