# Generated by Django 2.1.3 on 2018-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaLibrary', '0002_auto_20181120_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='Alias of the author, optional', max_length=50),
        ),
    ]
