# Generated by Django 2.1.3 on 2018-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaLibrary', '0003_auto_20181120_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, default='', help_text='Image of the Manga', upload_to='media/root'),
        ),
    ]
