# Generated by Django 2.1.3 on 2018-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaLibrary', '0004_auto_20181120_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, default='', help_text='Image of the Author', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image',
            field=models.ImageField(help_text='Image of the Manga', upload_to='img'),
        ),
    ]
